### ISSUE TITLE
Ability to play MPEG-4 Audio Book (.m4b)

### ISSUE THREAD

**Issue by Borewit** [webtorrent/webtorrent-desktop#1452]
Test data: one of the _MPEG-4 Audio Book_ (.m4b) files part of : https://archive.org/details/glories_of_ireland_1801_librivox

Related:
1.  #1450: adding the .m4b extension, which I thought I had done before...
2. Borewit/music-metadata#127 which is marked as bug, but it is in fact a workaround for an ugly tag appearing in these m4b file.

Issue is fixed if:
* [x] #1450 has been merged
* [x] we depend on a version of music-metadata fixing: Borewit/music-metadata#127
* [x] we can playback an m4b found in the [torrent provided]
(https://archive.org/details/glories_of_ireland_1801_librivox).
* [x] #1449 needs to be merged

**Comment by Borewit** [comment]
Test result:

![fix-m4b](https://user-images.githubusercontent.com/23255260/44229440-6405c200-a198-11e8-99e3-b11d38b27c70.jpg)

**Comment by Borewit** [comment]
Completed with PR #1449 merged.
