### ISSUE TITLE
Release WebTorrent Desktop 0.22.0

### ISSUE THREAD

**Issue by hicom150** [webtorrent/webtorrent-desktop#1727]
In order to prepare the release of the 0.22.0 version, I've added a task list so we can track the progress 😉 

- [x] Update `AUTHORS`
- [x] Update `CHANGELOG`
- [x] Update `package.json` dependencies
- [x] Update `migrations.js` version
- [ ] Create Release binaries (we need @feross help)

Feel free to add new tasks as needed 👍

PR #1730

**Comment by thevirajshelke** [comment]
When is the team making a release of v0.22.0?
There is a milestone named [v0.21.1](https://github.com/webtorrent/webtorrent-desktop/milestone/18)

So is it going to be v0.21.1 or v0.22.0?

I am just curious about the release date (tentative)

**Comment by feross** [comment]
@hicom150 I'm working on this release right now.

**Comment by feross** [comment]
Currently updating dependencies.

At the moment, npm reports ~70 vulnerabilities (almost all are probably false positive or don't affect us).

**Comment by feross** [comment]
This is complete now! WebTorrent Desktop 0.22.0 is released: https://github.com/webtorrent/webtorrent-desktop/blob/master/CHANGELOG.md#webtorrent-desktop-version-history
