### ISSUE TITLE
moar integration tests

### ISSUE THREAD

**Issue by dcposch** [webtorrent/webtorrent-desktop#965]
- [ ] create a large multifile torrent, restart app, take screenshot immediately. progress should be 💯, it should not reverify all the files.
- [ ] create a torrent using all the advanced options: private bit, custom announce list, comment. verify that the resulting torrent file has all of those set correctly.
- [ ] resize window, restart app, screenshot (should save bounds), start video, resize window, restart app, screenshot (should not window bounds when in the player)
- [ ] verify after each integration test that there were no uncaught errors
- [ ] write a manual testing checklist for the things we can't automate. setting the system torrent handler on mac, windows, and linux, auto start on login, dragging files onto the dock icon, etc

@feross

**Comment by feross** [comment]
Yes. 💯. These would be awesome improvements.

> write a manual testing checklist for the things we can't automate. setting the system torrent handler on mac, windows, and linux, auto start on login, dragging files onto the dock icon, etc

I have a list of manual things to test here: https://github.com/feross/webtorrent-desktop/blob/master/CONTRIBUTING.md#smoke-tests

We should probably move that to it's own file called `MANUAL_TESTS.md`.
